### ISSUE TITLE
All tests pass with rspec - everything fails with learn

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/playlister-static-generator-with-ar#9] opened 2015-09-14 20:46 UTC
I get the same error (as displayed below) for every test in the suite when I run learn. It also runs all the tests twice.

<img width="562" alt="screen shot 2015-09-14 at 4 42 44 pm" src="https://cloud.githubusercontent.com/assets/12770108/9861355/c33b105a-5aff-11e5-98fd-01aa0c52bc23.png">

**Comment by AnnJohn** [comment] 2015-09-15 19:21
Thanks @garettarrowood for raising this issue. This is on our product side, but I believe we'll soon be removing the remote build functionality so this will no longer be an issue.  Is that correct @kvignali?

**Comment by loganhasson** [comment] 2015-09-16 14:19
@AnnJohn this will still be an issue...this is a local build problem.

@garettarrowood will look into this ASAP!

**Comment by loganhasson** [comment] 2015-09-16 14:33
hey @aviflombaum @StevenNunez just briefly dug in...i'm actually seeing duplicate tests run using rspec or learn. it looks like the whole test suite is getting loaded and run twice, though i'm not exactly sure where it's happening. probably something to do with the `config.before` in the spec_helper where it's initializing the rake app (which reloads the environment)? maybe?

**Comment by pletcher** [comment] 2016-05-13 15:19
Hm, I'm not able to reproduce this -- and the double-testing mysteriously disappeared once RSpec deprecation warnings were quashed.

I'm going to leave this issue open for now, but will close it once I've addressed the other issues (as this will almost certainly be fixed by fixing those issues).

**Closed** 2016-05-13 18:42 UTC
Labels: icebox
